import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format, subDays, startOfDay, eachDayOfInterval } from 'date-fns';
import type { SleepRecord, FeedingRecord, DiaperRecord, TummyTimeRecord, PumpRecord, BabyProfile } from '../types';
import { TIME_DISPLAY } from './dateUtils';
import { userLongDatePattern } from './formatPreferencesStorage';

function safeParse<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as T) : fallback;
  } catch {
    return fallback;
  }
}

function safeDate(ts: number | undefined | null, fmt: string, fallback = '—'): string {
  try {
    if (!ts || !Number.isFinite(ts)) return fallback;
    return format(new Date(ts), fmt);
  } catch {
    return fallback;
  }
}

function getAgeLabel(birthDate: number | undefined): string {
  if (!birthDate) return '';
  const weeks = Math.floor((Date.now() - birthDate) / (7 * 24 * 3600000));
  if (weeks < 1) return `${Math.max(0, Math.floor((Date.now() - birthDate) / 86400000))} days`;
  return `${weeks} weeks`;
}

const CORAL = '#d4604a';
const DARK = '#2c1f1f';
const MUTED = '#9a8080';
const LIGHT_BG = '#faf7f2';

function drawBrandHeader(doc: jsPDF, isPremium: boolean, babyName: string, dateRange: string, age: string) {
  doc.setFillColor(250, 247, 242);
  doc.rect(0, 0, 210, 52, 'F');

  doc.setFontSize(20);
  doc.setTextColor(CORAL);
  doc.text('cradl', 14, 18);
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text('The app that understands.', 14, 24);

  doc.setFontSize(10);
  doc.setTextColor(CORAL);
  doc.text(isPremium ? 'PRO REPORT' : 'WEEKLY SUMMARY', 196, 14, { align: 'right' });

  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(dateRange, 196, 20, { align: 'right' });

  doc.setFontSize(14);
  doc.setTextColor(DARK);
  doc.text(`${babyName}'s week.`, 14, 38);

  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  const dateLine = `${age}${age ? ' · ' : ''}Report generated ${format(new Date(), userLongDatePattern())}`;
  doc.text(dateLine, 14, 45);
}

function drawStatsGrid(doc: jsPDF, y: number, stats: { label: string; value: string }[]) {
  const cols = Math.min(stats.length, 4);
  const colW = (196 - 14) / cols;
  let row = 0;
  stats.forEach((s, i) => {
    const col = i % cols;
    if (i > 0 && col === 0) row++;
    const x = 14 + col * colW;
    const yOff = y + row * 22;
    doc.setFontSize(16);
    doc.setTextColor(DARK);
    doc.text(s.value, x, yOff);
    doc.setFontSize(7);
    doc.setTextColor(MUTED);
    doc.text(s.label.toUpperCase(), x, yOff + 5);
  });
  return y + (row + 1) * 22 + 4;
}

function drawSectionHeader(doc: jsPDF, y: number, title: string): number {
  doc.setFontSize(11);
  doc.setTextColor(DARK);
  doc.text(title, 14, y);
  return y + 7;
}

function drawDayChart(doc: jsPDF, y: number, dayLabels: string[], values: number[], unit: string, barColor: string): number {
  const chartW = 170;
  const barW = chartW / 7;
  const maxVal = Math.max(...values, 1);
  const maxBarH = 24;
  const x0 = 14;

  dayLabels.forEach((label, i) => {
    const barH = (values[i] / maxVal) * maxBarH;
    const bx = x0 + i * barW + barW * 0.2;
    const bw = barW * 0.6;
    doc.setFillColor(barColor);
    doc.roundedRect(bx, y + maxBarH - barH, bw, Math.max(barH, 1), 1, 1, 'F');

    doc.setFontSize(7);
    doc.setTextColor(MUTED);
    doc.text(label, bx + bw / 2, y + maxBarH + 5, { align: 'center' });

    doc.setFontSize(6);
    doc.setTextColor(DARK);
    const vLabel = values[i] > 0 ? `${values[i]}${unit}` : '0';
    doc.text(vLabel, bx + bw / 2, y + maxBarH - barH - 2, { align: 'center' });
  });

  return y + maxBarH + 12;
}

function drawFooter(doc: jsPDF, page: number, total: number, isPremium: boolean) {
  doc.setFontSize(7);
  doc.setTextColor(MUTED);
  const prefix = isPremium ? 'Generated by Cradl PRO' : 'Generated by Cradl';
  doc.text(`${prefix} · cradl.app · ${format(new Date(), userLongDatePattern())}`, 14, 288);
  doc.text(`Page ${page} of ${total}`, 196, 288, { align: 'right' });
}

export function generatePediatricReport(isPremium: boolean = false) {
  try {
    const doc = new jsPDF();

    const babyProfile = safeParse<BabyProfile | null>('babyProfile', null);
    const sleepHistory = safeParse<SleepRecord[]>('sleepHistory', []);
    const feedingHistory = safeParse<FeedingRecord[]>('feedingHistory', []);
    const diaperHistory = safeParse<DiaperRecord[]>('diaperHistory', []);
    const tummyTimeHistory = safeParse<TummyTimeRecord[]>('tummyTimeHistory', []);
    const pumpHistory = safeParse<PumpRecord[]>('pumpHistory', []);

    const babyName = babyProfile?.name ?? 'Baby';
    const parentName = babyProfile?.parentName ?? '';
    const age = getAgeLabel(babyProfile?.birthDate);

    const now = new Date();
    const weekStart = subDays(now, 6);
    const dateRange = `${format(weekStart, 'd')} – ${format(now, userLongDatePattern())}`;
    const sevenDaysAgo = startOfDay(weekStart).getTime();
    const days = eachDayOfInterval({ start: weekStart, end: now });
    const dayLabels = days.map(d => format(d, 'EEE').charAt(0));

    const recentSleep = sleepHistory.filter(s => s.startTime > sevenDaysAgo);
    const recentFeeding = feedingHistory.filter(f => (f.startTime ?? f.timestamp) > sevenDaysAgo);
    const recentDiaper = diaperHistory.filter(d => d.timestamp > sevenDaysAgo);
    const recentTummy = tummyTimeHistory.filter(t => t.startTime > sevenDaysAgo);

    const completedSleep = recentSleep.filter(s => s.endTime);
    const totalSleepMs = completedSleep.reduce((a, s) => a + ((s.endTime ?? 0) - s.startTime - (s.excludedMs ?? 0)), 0);
    const avgSleepPerDay = totalSleepMs / 7;
    const avgSleepH = (avgSleepPerDay / 3600000).toFixed(1);
    const totalSleepH = (totalSleepMs / 3600000).toFixed(1);

    const avgFeedInterval = recentFeeding.length > 1
      ? recentFeeding
          .sort((a, b) => (a.startTime ?? a.timestamp) - (b.startTime ?? b.timestamp))
          .slice(1)
          .reduce((acc, f, i) => acc + ((f.startTime ?? f.timestamp) - (recentFeeding[i].startTime ?? recentFeeding[i].timestamp)), 0) / (recentFeeding.length - 1)
      : 0;
    const avgIntervalH = avgFeedInterval > 0 ? (avgFeedInterval / 3600000).toFixed(1) : '0';

    const wetCount = recentDiaper.filter(d => d.type === 'pee' || d.type === 'both').length;
    const dirtyCount = recentDiaper.filter(d => d.type === 'poop' || d.type === 'both').length;

    const totalTummyMs = recentTummy.filter(t => t.endTime).reduce((a, t) => a + ((t.endTime ?? 0) - t.startTime - (t.excludedMs ?? 0)), 0);
    const tummyMins = Math.round(totalTummyMs / 60000);

    const feedTypes = recentFeeding.reduce((acc, f) => {
      const t = f.type ?? 'unknown';
      acc[t] = (acc[t] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
    const feedTypeStr = Object.keys(feedTypes).length > 0
      ? Object.entries(feedTypes).map(([t, c]) => `${t} (${c})`).join(', ')
      : '—';

    const sleepPerDay = days.map(d => {
      const ds = startOfDay(d).getTime();
      const de = ds + 86400000;
      const ms = completedSleep.filter(s => s.startTime >= ds && s.startTime < de)
        .reduce((a, s) => a + ((s.endTime ?? 0) - s.startTime - (s.excludedMs ?? 0)), 0);
      return parseFloat((ms / 3600000).toFixed(1));
    });

    const feedsPerDay = days.map(d => {
      const ds = startOfDay(d).getTime();
      const de = ds + 86400000;
      return recentFeeding.filter(f => {
        const t = f.startTime ?? f.timestamp;
        return t >= ds && t < de;
      }).length;
    });

    // ═══════ PAGE 1 ═══════
    drawBrandHeader(doc, isPremium, babyName, dateRange, age);
    let y = 56;

    const statsGrid = isPremium
      ? [
          { label: 'AVG SLEEP/DAY', value: `${avgSleepH} hrs` },
          { label: 'TOTAL SLEEP', value: `${totalSleepH} hrs` },
          { label: 'SLEEP SESSIONS', value: String(recentSleep.length) },
          { label: 'TOTAL FEEDS', value: String(recentFeeding.length) },
          { label: 'AVG FEEDS/DAY', value: (recentFeeding.length / 7).toFixed(1) },
          { label: 'AVG INTERVAL', value: `${avgIntervalH} hrs` },
          { label: 'NAPPY CHANGES', value: String(recentDiaper.length) },
          { label: `WET / DIRTY`, value: `${wetCount} / ${dirtyCount}` },
        ]
      : [
          { label: 'SLEEP SESSIONS', value: String(recentSleep.length) },
          { label: 'AVG SLEEP', value: `${Math.round(avgSleepPerDay / 60000)} min` },
          { label: 'TOTAL SLEEP', value: String(recentSleep.length) },
          { label: 'FEEDS', value: String(recentFeeding.length) },
          { label: 'AVG INTERVAL', value: `${avgIntervalH} hrs` },
          { label: 'FEED TYPES', value: feedTypeStr.length > 15 ? '—' : (feedTypeStr || '—') },
          { label: 'NAPPY CHANGES', value: String(recentDiaper.length) },
          { label: `WET / DIRTY`, value: `${wetCount} / ${dirtyCount}` },
        ];

    y = drawStatsGrid(doc, y, statsGrid);
    y += 2;

    // Sleep chart
    y = drawSectionHeader(doc, y, isPremium ? 'Sleep — 7-day overview' : 'Sleep');
    y = drawDayChart(doc, y, dayLabels, sleepPerDay, 'h', '#4080a0');

    if (isPremium) {
      y = drawSectionHeader(doc, y + 4, 'Feeds — 7-day overview');
      y = drawDayChart(doc, y, dayLabels, feedsPerDay, '', CORAL);
    } else {
      y = drawSectionHeader(doc, y + 4, 'Feeding');
      doc.setFontSize(9);
      doc.setTextColor(DARK);
      doc.text(`Total feeds this week ${recentFeeding.length}`, 14, y); y += 5;
      doc.text(`Average interval between feeds ${avgIntervalH} hrs`, 14, y); y += 5;
      doc.text(`Feed types recorded ${feedTypeStr}`, 14, y); y += 8;

      y = drawSectionHeader(doc, y, 'Nappies');
      doc.setFontSize(9);
      doc.setTextColor(DARK);
      doc.text(`Wet nappies ${wetCount}`, 14, y); y += 5;
      doc.text(`Dirty nappies ${dirtyCount}`, 14, y); y += 5;
      doc.text(`Average per day ${(recentDiaper.length / 7).toFixed(1)}`, 14, y); y += 8;

      y = drawSectionHeader(doc, y, 'For your GP');
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      const gpText = `Bring this report to your next appointment. It covers ${babyName}'s last 7 days of feeds, sleep, nappy output, and tummy time in one place.`;
      const gpLines = doc.splitTextToSize(gpText, 180);
      doc.text(gpLines, 14, y);
    }

    drawFooter(doc, 1, isPremium ? 4 : 2, isPremium);

    // ═══════ PAGE 2 ═══════
    doc.addPage();

    if (isPremium) {
      // INSIGHTS PAGE
      doc.setFillColor(250, 247, 242);
      doc.rect(0, 0, 210, 16, 'F');
      doc.setFontSize(11);
      doc.setTextColor(DARK);
      doc.text(`Insights — what the data is telling you`, 14, 11);
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text(dateRange, 196, 11, { align: 'right' });

      y = 24;
      const insights: string[] = [];

      if (recentFeeding.length > 0) {
        const avgFeeds = (recentFeeding.length / 7).toFixed(1);
        insights.push(`${babyName} is averaging ${avgFeeds} feeds per day this week.`);
      }
      if (completedSleep.length > 0) {
        const avgNapMin = Math.round(totalSleepMs / completedSleep.length / 60000);
        insights.push(`Average sleep session length is ${avgNapMin} minutes across ${completedSleep.length} sessions.`);

        const longest = completedSleep.reduce((best, s) => {
          const dur = (s.endTime ?? 0) - s.startTime - (s.excludedMs ?? 0);
          return dur > best.dur ? { dur, s } : best;
        }, { dur: 0, s: completedSleep[0] });
        if (longest.dur > 0) {
          const longestH = Math.floor(longest.dur / 3600000);
          const longestM = Math.round((longest.dur % 3600000) / 60000);
          const dayStr = safeDate(longest.s.startTime, 'EEEE');
          insights.push(`Longest sleep stretch was ${longestH}h ${longestM}m on ${dayStr}.`);
        }
      }
      if (tummyMins > 0) {
        insights.push(`Tummy time total: ${tummyMins} minutes this week.`);
      }

      doc.setFontSize(9);
      doc.setTextColor(DARK);
      insights.forEach(insight => {
        const lines = doc.splitTextToSize(`• ${insight}`, 180);
        doc.text(lines, 14, y);
        y += lines.length * 5 + 3;
      });

      y += 6;

      // Leap info
      y = drawSectionHeader(doc, y, 'Developmental context');
      doc.setFontSize(9);
      doc.setTextColor(DARK);
      const ageWeeks = babyProfile?.birthDate ? Math.floor((Date.now() - babyProfile.birthDate) / (7 * 86400000)) : null;
      if (ageWeeks != null) {
        doc.text(`${babyName} is ${ageWeeks} weeks old. Development is progressing normally.`, 14, y);
        y += 8;
      }

      y = drawSectionHeader(doc, y, 'Your personal playbook');
      doc.setFontSize(9);
      doc.setTextColor(DARK);
      const playbook = [
        `Total tummy time this week: ${tummyMins} min`,
        `Nappy output: ${wetCount} wet, ${dirtyCount} dirty (${(recentDiaper.length / 7).toFixed(1)}/day)`,
        `Sleep sessions: ${recentSleep.length} (avg ${avgSleepH}h/day)`,
      ];
      playbook.forEach(line => {
        doc.text(line, 14, y);
        y += 5;
      });

      drawFooter(doc, 2, 4, true);

      // ═══════ PAGE 3 - DETAILED LOGS + GROWTH ═══════
      doc.addPage();

      doc.setFillColor(250, 247, 242);
      doc.rect(0, 0, 210, 16, 'F');
      doc.setFontSize(11);
      doc.setTextColor(DARK);
      doc.text(`Detailed logs`, 14, 11);
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text(dateRange, 196, 11, { align: 'right' });

      y = 22;

      const allEvents: { ts: number; type: string; detail: string; dur: string }[] = [];

      recentFeeding.forEach(f => {
        const ts = f.startTime ?? f.timestamp;
        const type = f.type ?? 'Nurse';
        const dur = f.durationMs ? `${Math.round(f.durationMs / 60000)} min` : '—';
        const detail = f.segments?.length
          ? f.segments.map(s => `${s.type} ${Math.round((s.durationMs ?? 0) / 60000)}m`).join(', ')
          : type.charAt(0).toUpperCase() + type.slice(1);
        allEvents.push({ ts, type: 'Nurse', detail, dur });
      });

      completedSleep.forEach(s => {
        const durMs = (s.endTime ?? 0) - s.startTime - (s.excludedMs ?? 0);
        const h = Math.floor(durMs / 3600000);
        const m = Math.round((durMs % 3600000) / 60000);
        allEvents.push({ ts: s.startTime, type: 'Sleep', detail: s.position ?? 'Sleep', dur: h > 0 ? `${h}h ${m}m` : `${m} min` });
      });

      recentDiaper.forEach(d => {
        const label = d.type === 'both' ? 'Wet + dirty' : d.type === 'pee' ? 'Wet' : 'Dirty';
        allEvents.push({ ts: d.timestamp, type: 'Nappy', detail: label, dur: '—' });
      });

      recentTummy.filter(t => t.endTime).forEach(t => {
        const durMs = (t.endTime ?? 0) - t.startTime - (t.excludedMs ?? 0);
        allEvents.push({ ts: t.startTime, type: 'Tummy', detail: '—', dur: `${Math.round(durMs / 60000)} min` });
      });

      pumpHistory.filter(p => p.timestamp > sevenDaysAgo).forEach(p => {
        const ml = (p.volumeLeftMl ?? 0) + (p.volumeRightMl ?? 0);
        allEvents.push({ ts: p.timestamp, type: 'Pump', detail: `${p.side} ${ml ? ml + 'ml' : ''}`, dur: `${Math.round(p.durationMs / 60000)} min` });
      });

      allEvents.sort((a, b) => a.ts - b.ts);

      const showEvents = allEvents.slice(0, 50);

      if (showEvents.length > 0) {
        autoTable(doc, {
          startY: y,
          head: [['DATE', 'TIME', 'TYPE', 'DETAIL', 'DURATION']],
          body: showEvents.map(e => [
            safeDate(e.ts, 'EEE dd'),
            safeDate(e.ts, TIME_DISPLAY()),
            e.type,
            e.detail,
            e.dur,
          ]),
          theme: 'plain',
          styles: { fontSize: 7, cellPadding: 2, textColor: DARK },
          headStyles: { fontSize: 6, textColor: MUTED, fontStyle: 'bold' },
          alternateRowStyles: { fillColor: [250, 247, 242] },
        });
        y = (doc as any).lastAutoTable?.finalY ?? y + 10;
      } else {
        doc.setFontSize(9);
        doc.setTextColor(MUTED);
        doc.text('No logs recorded this week.', 14, y);
        y += 6;
        doc.text('Start tracking feeds, sleeps and nappies in the app to see your full log here.', 14, y);
        y += 10;
      }

      y += 6;

      // Growth
      const growthData = safeParse<{ id: string; date: number; weightKg?: number; heightCm?: number; headCircumferenceCm?: number }[]>('growthMeasurements', []);
      if (growthData.length > 0) {
        y = drawSectionHeader(doc, y, 'Growth — WHO percentile bands');
        doc.setFontSize(9);
        doc.setTextColor(DARK);
        const latest = growthData.sort((a, b) => b.date - a.date)[0];
        if (latest.weightKg) doc.text(`${latest.weightKg} kg — Weight`, 14, y), y += 5;
        if (latest.heightCm) doc.text(`${latest.heightCm} cm — Length`, 14, y), y += 5;
        if (latest.headCircumferenceCm) doc.text(`${latest.headCircumferenceCm} cm — Head circumference`, 14, y), y += 5;
        y += 4;
      }

      if (allEvents.length > showEvents.length) {
        doc.setFontSize(8);
        doc.setTextColor(MUTED);
        doc.text(`Full log for all 7 days available in the Cradl app — History tab.`, 14, y);
      }

      drawFooter(doc, 3, 4, true);

      // ═══════ PAGE 4 - WELLBEING ═══════
      doc.addPage();

      doc.setFillColor(250, 247, 242);
      doc.rect(0, 0, 210, 16, 'F');
      doc.setFontSize(11);
      doc.setTextColor(DARK);
      const wellbeingTitle = parentName ? `Your wellbeing, ${parentName}` : 'Your wellbeing';
      doc.text(wellbeingTitle, 14, 11);
      doc.setFontSize(7);
      doc.setTextColor(MUTED);
      doc.text('Completely private — for you', 196, 11, { align: 'right' });

      y = 22;
      doc.setFontSize(9);
      doc.setTextColor(DARK);
      doc.text('This section is for you — not the baby.', 14, y);
      y += 8;

      const mumSleep = safeParse<{ date: string; sleepRange: string }[]>('mumSleepHistory', []);
      const moodLog = safeParse<{ date: string; mood: string }[]>('cradl-mood-log', []);
      const pelvicFloor = safeParse<{ date: string; completed: boolean }[]>('pelvicFloorHistory', []);

      const recentMumSleep = mumSleep.filter(s => {
        const d = new Date(s.date).getTime();
        return d > sevenDaysAgo;
      });
      const mumSleepStr = recentMumSleep.length > 0
        ? `Avg ${(recentMumSleep.length).toFixed(0)} entries logged`
        : '— (not yet logged)';

      const recentMood = moodLog.filter(m => {
        const d = new Date(m.date).getTime();
        return d > sevenDaysAgo;
      });
      const moodStr = recentMood.length > 0
        ? recentMood.map(m => m.mood.charAt(0).toUpperCase() + m.mood.slice(1)).join(' · ')
        : '— (not yet logged)';

      const recentPelvic = pelvicFloor.filter(p => {
        const d = new Date(p.date).getTime();
        return d > sevenDaysAgo;
      });
      const pelvicDone = recentPelvic.filter(p => p.completed).length;
      const pelvicStr = recentPelvic.length > 0 ? `${pelvicDone} of 7 days completed` : '— (not yet logged)';

      doc.text(`Your sleep this week: ${mumSleepStr}`, 14, y); y += 6;
      doc.text(`Mood check-ins: ${moodStr}`, 14, y); y += 6;
      doc.text(`Pelvic floor sessions: ${pelvicStr}`, 14, y); y += 12;

      // Mood chart
      if (recentMood.length > 0) {
        y = drawSectionHeader(doc, y, 'Your mood this week');
        doc.setFontSize(8);
        days.forEach((d, i) => {
          const ds = format(d, 'yyyy-MM-dd');
          const entry = recentMood.find(m => m.date === ds);
          const label = format(d, 'EEE').charAt(0);
          const mood = entry?.mood ?? '—';
          const x = 14 + i * 24;
          doc.setTextColor(MUTED);
          doc.text(label, x, y);
          doc.setTextColor(DARK);
          doc.text(mood.charAt(0).toUpperCase() + mood.slice(1, 4), x, y + 5);
        });
        y += 14;
      }

      // EPDS
      const epds = safeParse<{ totalScore: number; completedAt: string }[]>('epdsResponses', []);
      if (epds.length > 0) {
        const latest = epds.sort((a, b) => b.completedAt.localeCompare(a.completedAt))[0];
        y = drawSectionHeader(doc, y, 'Edinburgh Postnatal Depression Scale — this month');
        doc.setFontSize(9);
        doc.setTextColor(DARK);
        const threshold = latest.totalScore >= 13 ? 'above clinical threshold — please speak with your GP' : 'below clinical threshold';
        doc.text(`Score: ${latest.totalScore}/30 — ${threshold}.`, 14, y);
        y += 8;
      }

      // GP notes
      y = drawSectionHeader(doc, y + 4, 'Notes for your GP appointment');
      doc.setFontSize(8);
      doc.setTextColor(DARK);

      const gpQuestions = safeParse<string>('cradl-gp-questions', '');
      const gpNotes: string[] = [];

      if (growthData.length > 0) {
        const latest = growthData.sort((a, b) => b.date - a.date)[0];
        if (latest.weightKg) gpNotes.push(`Weight at last check: ${latest.weightKg} kg`);
      }
      gpNotes.push(`Feeding: ${feedTypeStr}`);
      if (completedSleep.length > 0) {
        const avgNap = Math.round(totalSleepMs / completedSleep.length / 60000);
        gpNotes.push(`Naps averaging ${avgNap} min`);
      }
      if (parentName) gpNotes.push(`Mum recovery: Pelvic floor ${pelvicStr.toLowerCase()}`);

      gpNotes.forEach(note => {
        doc.text(note, 14, y);
        y += 5;
      });

      if (gpQuestions) {
        y += 4;
        doc.setFontSize(8);
        doc.setTextColor(DARK);
        doc.text('Your questions for the appointment:', 14, y);
        y += 5;
        const qLines = doc.splitTextToSize(gpQuestions, 180);
        doc.text(qLines, 14, y);
        y += qLines.length * 4 + 4;
      } else {
        y += 4;
        doc.setFontSize(8);
        doc.setTextColor(MUTED);
        doc.text('Your questions for the appointment:', 14, y);
        y += 5;
        doc.text('Write your questions here before you go:', 14, y);
        y += 10;
      }

      // Encouragement
      y = Math.max(y, 260);
      doc.setFontSize(10);
      doc.setTextColor(CORAL);
      doc.text(`You are doing an extraordinary job${parentName ? `, ${parentName}` : ''}.`, 14, y);
      doc.setFontSize(7);
      doc.setTextColor(MUTED);
      doc.text('cradl.app', 14, y + 5);

      drawFooter(doc, 4, 4, true);

    } else {
      // ═══════ FREE PAGE 2 ═══════
      doc.setFillColor(250, 247, 242);
      doc.rect(0, 0, 210, 16, 'F');
      doc.setFontSize(11);
      doc.setTextColor(DARK);
      doc.text(`${babyName}'s detailed logs`, 14, 11);
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text(dateRange, 196, 11, { align: 'right' });

      y = 22;

      const allEvents: { ts: number; type: string; detail: string; dur: string }[] = [];
      recentFeeding.forEach(f => {
        const ts = f.startTime ?? f.timestamp;
        const detail = f.type ? f.type.charAt(0).toUpperCase() + f.type.slice(1) : 'Nurse';
        const dur = f.durationMs ? `${Math.round(f.durationMs / 60000)} min` : '—';
        allEvents.push({ ts, type: 'Nurse', detail, dur });
      });
      completedSleep.forEach(s => {
        const durMs = (s.endTime ?? 0) - s.startTime - (s.excludedMs ?? 0);
        const m = Math.round(durMs / 60000);
        allEvents.push({ ts: s.startTime, type: 'Sleep', detail: s.position ?? 'Sleep', dur: `${m} min` });
      });
      recentDiaper.forEach(d => {
        const label = d.type === 'both' ? 'Wet + dirty' : d.type === 'pee' ? 'Wet' : 'Dirty';
        allEvents.push({ ts: d.timestamp, type: 'Nappy', detail: label, dur: '—' });
      });
      recentTummy.filter(t => t.endTime).forEach(t => {
        const durMs = (t.endTime ?? 0) - t.startTime;
        allEvents.push({ ts: t.startTime, type: 'Tummy', detail: '—', dur: `${Math.round(durMs / 60000)} min` });
      });
      allEvents.sort((a, b) => a.ts - b.ts);

      if (allEvents.length > 0) {
        autoTable(doc, {
          startY: y,
          head: [['TIME', 'TYPE', 'DETAIL', 'DURATION / NOTE']],
          body: allEvents.slice(0, 30).map(e => [
            safeDate(e.ts, `${TIME_DISPLAY()}`),
            e.type,
            e.detail,
            e.dur,
          ]),
          theme: 'plain',
          styles: { fontSize: 7, cellPadding: 2, textColor: DARK },
          headStyles: { fontSize: 6, textColor: MUTED, fontStyle: 'bold' },
          alternateRowStyles: { fillColor: [250, 247, 242] },
        });
        y = (doc as any).lastAutoTable?.finalY ?? y + 10;
      } else {
        doc.setFontSize(9);
        doc.setTextColor(MUTED);
        doc.text('No logs recorded this week.', 14, y);
        y += 5;
        doc.text('Start tracking feeds, sleeps and nappies in the app to see your full log here.', 14, y);
        y += 10;
      }

      y += 8;

      // Wellbeing (brief for free)
      const wellbeingTitle = parentName ? `Your wellbeing, ${parentName}` : 'Your wellbeing';
      y = drawSectionHeader(doc, y, wellbeingTitle);
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text('This section is for you — not for the baby.', 14, y); y += 5;
      doc.text('Track your own sleep, mood, and recovery in the app and this section', 14, y); y += 4;
      doc.text('will show your personal wellbeing summary alongside the baby\'s data.', 14, y); y += 8;

      doc.setFontSize(9);
      doc.setTextColor(DARK);
      doc.text('Your sleep this week: — (not yet logged)', 14, y); y += 5;
      doc.text('Mood check-ins: — (not yet logged)', 14, y); y += 5;
      doc.text('Pelvic floor sessions: — (not yet logged)', 14, y); y += 12;

      y = drawSectionHeader(doc, y, 'Notes for your GP');
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text('Questions or observations you want to raise:', 14, y);
      y += 12;

      // Upsell
      doc.setFillColor(250, 247, 242);
      doc.roundedRect(14, y, 182, 24, 4, 4, 'F');
      doc.setFontSize(10);
      doc.setTextColor(DARK);
      doc.text('Unlock the full report with Cradl PRO', 20, y + 9);
      doc.setFontSize(7);
      doc.setTextColor(MUTED);
      doc.text('Detailed logs, insights, growth percentiles, and your personal playbook — from £3.99/mo. cradl.app/pro →', 20, y + 16);

      drawFooter(doc, 2, 2, false);
    }

    doc.save(`cradl-baby-report${isPremium ? '-pro' : ''}.pdf`);
  } catch (e) {
    console.error('[Cradl] generatePediatricReport failed:', e);
    throw e;
  }
}
